### PR TITLE
CMS 12 support 

### PR DESCRIPTION
**Pull request by OMGPizzaGuy**
This is a first pass attempt at supporting both CMS 11 & CMS12. CMS11 appears to work correctly with this. CMS12 does not have the option working yet.

Any insights or critiques are welcome. Thanks!

### CODE REVIEW

**Comment by OMGPizzaGuy** [comment]
Ah. I see I don't have this working in CMS-12 yet. I confused normal compare with the features provided. There's still work to be done.

**Comment by OMGPizzaGuy** [comment]
This appears to be functional now in both CMS 11 & 12.

**Comment by OMGPizzaGuy** [comment]
Checking up on this - Any feedback for this PR? Does it need to be split into separate PRs?

**Comment by davidknipe** [comment]
Thank you so much for the contribution! I will check into this ASAP as its a much requested feature. Apologies but I didn't see the email this first time

**Comment by OMGPizzaGuy** [comment]
Heads up - this worked in foundation-mvc-cms, but I'm running into some issues in my real project we're finally upgrading.
There will be some fixes added this week.

**Comment by OMGPizzaGuy** [comment]
Last change was close, but not quite right - the razor source generator is attempting to compile views both referenced in the package and the versions copied into the project. Still investigating.

**Comment by OMGPizzaGuy** [comment]
I think this is now working. It seems the right answer is probably to zip the module and use precompiled views in .NET5+, but this could do for the moment

**Comment by OMGPizzaGuy** [comment]
@davidknipe - Any chance of moving forward with this? I am willing to become a maintainer for the project.

**Comment by davidknipe** [comment]
I've added you as a collaborator. Thanks for taking this on, CMS 12 compatibility is a big request from the community!

**Comment by OMGPizzaGuy** [comment]
Thank you! I'll be working on a release this week, starting with completing this PR

**Comment by davidknipe** [comment]
> Thank you! I'll be working on a release this week, starting with completing this PR

Thank **you** for taking this on! I have worked on another add-on that targets CMS 11 and CMS 12 if you wanted to some inspiration on dual targeting: https://github.com/unrvld/ODP.VisitorGroups. Or you could split the version numbering so v2.x targets CMS 12. Let me know your thoughts :)

**Comment by OMGPizzaGuy** [comment]
I am running into a problem with multi targeting, which is the upload to https://nuget.optimizely.com responds "Invalid packages detected" with no additional details. My guess would be a validation check on upload is checking the nuspec dependencies and does not like it.

**Comment by clintcfavor** [comment]
Hi! I'm trying to run this addon in CMS 12 but I'm getting 404 errors for `VisualCompare`. Please see screenshot below
image

What might I have missed?

**Comment by OMGPizzaGuy** [comment]
@clintcfavor Hello! Could you open an issue for this so we can track it properly? Any additional details on that issue would be helpful as well, such as package versions or any logs you may have. I cannot tell much from the screenshot alone. This work item has been completed and any additional comments could be easily forgotten.

**Pull request merged**
